name: Sync GitHub to GitLab

on:
  push:
    branches: ['*']
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "https://CarmiBanxe:${GITLAB_TOKEN}@gitlab.com/carmibanxe1/banxe-training-data.git"
          git push gitlab --all --force
          git push gitlab --tags --force
